name: flutter_codex
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  retrofit: ^4.4.1
  flutter_inappwebview: ^6.1.5
  flutter_easyloading: ^3.0.5
  flutter_blue_plus: ^1.35.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  retrofit_generator: ^9.1.5
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
